spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5433/resource_booking_db
spring.datasource.username=resource_user
spring.datasource.password=resource_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

booking.locking-strategy=optimistic

app.security.jwt.secret=sl14asdas14ot-eng414124ine-loc34asd13sd41al-d1242ev-j1asdsa24wt-121asd23e3cr2eaasd141t-8Nq4vT7zsD3fG0kJwE
app.security.jwt.access-token-expiration-minutes=15
app.security.refresh-token.expiration-days=7
app.security.cookie.secure=false
app.security.cookie.same-site=Lax