spring.application.name=server

spring.datasource.url=jdbc:postgresql://localhost:5432/resource_booking_db
spring.datasource.username=resource_user
spring.datasource.password=resource_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect