CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    booked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    cancelled_at TIMESTAMPTZ,

    CONSTRAINT fk_bookings_slot
        FOREIGN KEY (slot_id)
        REFERENCES slots(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bookings_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_bookings_status
        CHECK (status IN ('CONFIRMED', 'CANCELLED')),

    CONSTRAINT chk_bookings_cancelled_at
        CHECK (
            (status = 'CANCELLED' AND cancelled_at IS NOT NULL)
            OR
            (status = 'CONFIRMED' AND cancelled_at IS NULL)
        )
);

CREATE INDEX idx_bookings_user
    ON bookings(user_id);

CREATE UNIQUE INDEX uk_bookings_confirmed_slot
    ON bookings(slot_id)
    WHERE status = 'CONFIRMED';

INSERT INTO users (id, name, email, password_hash, role)
VALUES (
    1,
    'Phase Two User',
    'phase2.user@example.com',
    'phase2-placeholder-password-hash',
    'USER'
);

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    (SELECT MAX(id) FROM users)
);